@startuml 


entity IfcVirtualElement <<DefinedInThisDiagram>>
{
  *ObjectType : text = Combination of surfaces
  ObjectPlacement
  Representation
  +PredefinedType : text = USERDEFINED
}

entity IfcClassificationReference <<UndefinedEntity>> 


IfcVirtualElement --|{ IfcClassificationReference : IfcRelAssociatesClassification

entity "IfcProductDefinitionShape-TINwithBreaklines" <<DefinedInAnotherDiagram>>

IfcVirtualElement::Representation --|| "IfcProductDefinitionShape-TINwithBreaklines"

entity IfcLocalPlacement <<UndefinedEntity>>
IfcVirtualElement::ObjectPlacement --|| IfcLocalPlacement

@enduml
