@startuml 


entity IfcCourse <<DefinedInThisDiagram>>
{
  *ObjectPlacement
  *Representation
  ..
  *HasAssociations
  +IsDefinedBy
  +ConnectedTo
  +ConnectedFrom
}

entity IfcClassificationReference <<DefinedInAnotherDiagram>>

entity IfcPropertySet-IfcCourse <<DefinedInThisDiagram>>
{
    bSF_Pset_SurfaceCourse
    bSF_Pset_CourseCommon
    Pset_CourseCommon
    Pset_BoundedCourseCommon
    Pset_CourseApplicationConditions
}

'entity bSF_Pset_SurfaceCourse <<DefinedInAnotherDiagram>>


'protocol bSF_Pset_CourseCommon <<DefinedInAnotherDiagram>>


entity Qto_CourseBaseQuantities <<UndefinedEntity>>

'protocol Pset_CourseCommon <<UndefinedEntity>>

'protocol Pset_BoundedCourseCommon <<UndefinedEntity>>

'protocol Pset_CourseApplicationConditions <<Undefinedentity>>


IfcCourse::HasAssociations --|{ IfcClassificationReference : IfcRelAssociatesClassification

entity "IfcProductDefinitionShape-TINwithBreaklines" <<DefinedInAnotherDiagram>>

IfcCourse::Representation --|| "IfcProductDefinitionShape-TINwithBreaklines"

entity IfcLocalPlacement <<UndefinedEntity>>
IfcCourse::ObjectPlacement --|| IfcLocalPlacement

IfcCourse::IsDefinedBy --o| "IfcPropertySet-IfcCourse" : IfcRelDefinesByProperties
'IfcCourse::IsDefinedBy --o| bSF_Pset_CourseCommon : IfcRelDefinesByProperties
'IfcCourse::IsDefinedBy --o| bSF_Pset_SurfaceCourse  : IfcRelDefinesByProperties
'IfcCourse::IsDefinedBy --o| Pset_CourseCommon : IfcRelDefinesByProperties
'IfcCourse::IsDefinedBy --o| Pset_BoundedCourseCommon : IfcRelDefinesByProperties
'IfcCourse::IsDefinedBy --o| Pset_CourseApplicationConditions : IfcRelDefinesByProperties

IfcCourse::IsDefinedBy --o| Qto_CourseBaseQuantities : IfcRelDefinesByProperties

entity IfcEarthWorksCut <<DefinedInAnotherDiagram>>

entity IfcEarthWorksFill <<DefinedInAnotherDiagram>>


entity "IfcRelConnectsElements-CourseToCut" <<DefinedInThisDiagram>>
{
  *RelatingElement
  *RelatedElement
}

"IfcRelConnectsElements-CourseToCut::RelatingElement" --|| IfcEarthWorksCut
"IfcRelConnectsElements-CourseToCut::RelatedElement" }o--|| IfcCourse::ConnectedFrom


entity "IfcRelConnectsElements-CourseToCourse" <<DefinedInThisDiagram>>
{
  *RelatingElement
}


"IfcRelConnectsElements-CourseToCourse::RelatingElement" }o--|| IfcCourse::ConnectedTo
"IfcRelConnectsElements-CourseToCourse::RelatedElement" }o--|| IfcCourse::ConnectedFrom


entity "IfcRelConnectsElements-CourseToFill" <<DefinedInThisDiagram>>
{
  *RelatingElement
  *RelatedElement
}

"IfcRelConnectsElements-CourseToFill::RelatingElement" --|| IfcEarthWorksFill
"IfcRelConnectsElements-CourseToFill::RelatedElement" }o--|| IfcCourse::ConnectedFrom




@enduml
