@startuml 

entity IFC_step_file <<DefinedInAnotherDiagram>>

entity IfcProject <<DefinedInAnotherDiagram>>
IFC_step_file--||IfcProject

entity IfcSite <<DefinedInAnotherDiagram>>
IfcProject||--|{IfcSite : IfcRelAggregates


entity IfcRoad <<DefinedInAnotherDiagram>> 
IfcSite||--o{IfcRoad : IfcRelAggregates


entity IfcVirtualElement <<DefinedInAnotherDiagram>>
IfcRoad||--||IfcVirtualElement : IfcRelContainedInSpatialStructure

entity IfcGeomodel <<DefinedInAnotherDiagram>>

IfcSite||--|{IfcGeomodel : IfcRelContainedInSpatialStructure

entity "IfcGeotechnicalStratum-Terrain" <<DefinedInAnotherDiagram>>
IfcGeomodel||--|{"IfcGeotechnicalStratum-Terrain":IfcRelAggregates
entity "IfcGeotechnicalStratum-Rock bed" <<DefinedInAnotherDiagram>>
IfcGeomodel||--o{"IfcGeotechnicalStratum-Rock bed":IfcRelAggregates


entity IfcPavement <<DefinedInAnotherDiagram>>
IfcRoad||--|{IfcPavement : IfcRelContainedInSpatialStructure

entity "IfcEarthWorksCut-Rock" <<DefinedInAnotherDiagram>>
IfcRoad}o.."IfcEarthWorksCut-Rock": IfcRelReferencedInSpatialStructure
entity "IfcEarthWorksCut-Soil" <<DefinedInAnotherDiagram>>
IfcRoad}o.."IfcEarthWorksCut-Soil": IfcRelReferencedInSpatialStructure


"IfcGeotechnicalStratum-Rock bed"||--o{"IfcEarthWorksCut-Rock" : IfcRelVoidsElement
"IfcGeotechnicalStratum-Terrain"||--o{"IfcEarthWorksCut-Soil" : IfcRelVoidsElement

entity IfcEarthWorksFill <<DefinedInAnotherDiagram>>
IfcRoad||--|{IfcEarthWorksFill : IfcRelContainedInSpatialStructure

IfcEarthWorksFill..IfcEarthWorksFill:IfcRelConnectsElements

"IfcEarthWorksCut-Rock"..IfcEarthWorksFill :IfcRelConnectsElements 
"IfcEarthWorksCut-Soil"..IfcEarthWorksFill :IfcRelConnectsElements 

entity IfcCourse <<DefinedInAnotherDiagram>>
IfcPavement||--|{IfcCourse :IfcRelAggregates

IfcCourse..IfcCourse:IfcRelConnectsElements
IfcCourse..IfcEarthWorksFill:IfcRelConnectsElements

entity IfcKerb <<DefinedInAnotherDiagram>>
IfcPavement||--o{IfcKerb :IfcRelAggregates
IfcCourse..IfcKerb:IfcRelConnectsElements


entity IfcAlignment <<DefinedInAnotherDiagram>>
IfcProject||--o{IfcAlignment : IfcRelAggregates


IfcRoad||..||IfcAlignment : IfcRelReferencedInSpatialStructure



@enduml
