@startuml 

entity "IfcEarthWorksCut-Soil" <<DefinedInThisDiagram>>
{
  ObjectPlacement
  Representation
  *PredefinedType : text = TOPSOILREMOVAL | CUT
}

entity IfcClassificationReference <<UndefinedEntity>>
"IfcEarthWorksCut-Soil" --|{ IfcClassificationReference : IfcRelAssociatesClassification


protocol "IfcElementQuantity-Cut" <<DefinedInThisDiagram>>
{
  Qto_EarthworksCutBaseQuantities
}

entity IfcLocalPlacement <<UndefinedEntity>>
"IfcEarthWorksCut-Soil::ObjectPlacement" --|| IfcLocalPlacement


entity "IfcProductDefinitionShape-BrepwithBreaklines" <<DefinedInAnotherDiagram>>
"IfcEarthWorksCut-Soil::Representation" --|| "IfcProductDefinitionShape-BrepwithBreaklines"

"IfcEarthWorksCut-Soil" --o| "IfcElementQuantity-Cut"  : IfcRelDefinesByProperties

@enduml