@startuml 

entity IfcProject <<DefinedInThisDiagram>>
{
  RepresentationContexts
  UnitsInContext
}

entity IfcGeometricRepresentationContext-3D <<DefinedInAnotherDiagram>>

entity IfcUnitAssignment <<UndefinedEntity>>

entity IfcAlignment <<DefinedInAnotherDiagram>>
IfcProject --o{ IfcAlignment : IfcRelAggregates

entity IfcSite <<DefinedInAnotherDiagram>>
IfcProject --|{ IfcSite : IfcRelAggregates

protocol "IfcPropertySet-Project" <<DefinedInThisDiagram>>
{
  Pset_ProjectCommon
}

protocol "IfcPropertySet-bSFProject" <<DefinedInThisDiagram>>
{
  bSF_Project
}

entity IfcClassification <<UndefinedEntity>>

IfcProject::RepresentationContexts --|| "IfcGeometricRepresentationContext-3D"
IfcProject::UnitsInContext --|| IfcUnitAssignment
IfcProject --|{IfcClassification : IfcRelAssociatesClassification
IfcProject --o| "IfcPropertySet-Project" : IfcRelDefinesByProperties
IfcProject --o| "IfcPropertySet-bSFProject" : IfcRelDefinesByProperties

@enduml
