@startuml 

entity "IfcGeotechnicalStratum-Rock bed" <<DefinedInThisDiagram>>
{
  ObjectPlacement
  Representation
  *PredefinedType : text = SOLID
}

entity IfcLocalPlacement <<UndefinedEntity>>
"IfcGeotechnicalStratum-Rock bed::ObjectPlacement" --|| IfcLocalPlacement

entity "IfcProductDefinitionShape-TIN" <<DefinedInAnotherDiagram>>
"IfcGeotechnicalStratum-Rock bed::Representation" --|| "IfcProductDefinitionShape-TIN"

entity IfcClassificationReference <<UndefinedEntity>>
"IfcGeotechnicalStratum-Rock bed" --|{ IfcClassificationReference : IfcRelAssociatesClassification

entity "IfcEarthWorksCut-Rock" <<DefinedInAnotherDiagram>>
"IfcGeotechnicalStratum-Rock bed" ||--o{ "IfcEarthWorksCut-Rock": IfcRelVoidsElement

protocol "IfcPropertySet-bSFStratum" <<DefinedInAnotherDiagram>>

"IfcGeotechnicalStratum-Rock bed" --o| "IfcPropertySet-bSFStratum" : IfcRelDefinesByProperties


@enduml
