@startuml 

entity "IfcProductDefinitionShape-SolidwithBreaklines" <<DefinedInThisDiagram>>
{
  Representations
}

entity "IfcShapeRepresentation-SectionedSolid" <<DefinedInThisDiagram>>
{
  *RepresentationIdentifier : text = Body
  *RepresentationType : text = AdvancedSweptSolid
  Items
  +OfShapeAspect : $
}

entity IfcSectionedSolidHorizontal <<UndefinedEntity>>

entity "IfcShapeRepresentation-Breaklines" <<DefinedInAnotherDiagram>>

"IfcProductDefinitionShape-SolidwithBreaklines::Representations" --|| "IfcShapeRepresentation-SectionedSolid"
"IfcProductDefinitionShape-SolidwithBreaklines::Representations" --o| "IfcShapeRepresentation-Breaklines"

"IfcShapeRepresentation-SectionedSolid::Items"--||IfcSectionedSolidHorizontal

entity IfcShapeAspect <<DefinedInAnotherDiagram>>
"IfcProductDefinitionShape-SolidwithBreaklines"--o{IfcShapeAspect


@enduml


