@startuml 

entity IfcRoad <<DefinedInAnotherDiagram>>

entity IfcAlignment <<DefinedInThisDiagram>>
{
    ObjectPlacement
    Representation
}

entity IfcProductDefinitionShape-Alignment <<DefinedInAnotherDiagram>>
IfcAlignment::Representation--||"IfcProductDefinitionShape-Alignment" 

entity IfcLocalPlacement <<UndefinedEntity>>
IfcAlignment::ObjectPlacement--||IfcLocalPlacement

entity IfcClassificationReference <<UndefinedEntity>>
IfcAlignment --|{ IfcClassificationReference : IfcRelAssociatesClassification

entity IfcReferent <<DefinedInThisDiagram>>
{
    ObjectPlacement
    Representation
	PredefinedType : text = STATION | SUPERELEVATIONEVENT | WIDTHEVENT
}

entity IfcProductDefinitionShape-Annotation <<DefinedInAnotherDiagram>>
IfcReferent::Representation--o|"IfcProductDefinitionShape-Annotation" 

entity IfcLinearPlacement <<UndefinedEntity>>

IfcReferent::ObjectPlacement--||IfcLinearPlacement

IfcAlignment --o{ IfcReferent : IfcRelNests

entity IfcAlignmentHorizontal <<DefinedInAnotherDiagram>>
entity IfcAlignmentVertical <<DefinedInAnotherDiagram>>
entity IfcAlignmentCant <<UndefinedEntity>>

<> sequence
IfcAlignment -- sequence : IfcRelNests
sequence --|| IfcAlignmentHorizontal
sequence --|| IfcAlignmentVertical
sequence --o|IfcAlignmentCant


IfcRoad||--IfcAlignment : IfcRelReferencedInSpatialStructure

protocol "IfcPropertySet-Alignment" <<DefinedInThisDiagram>>
{
  Pset_LinearReferencingMethod
}
IfcAlignment --o| "IfcPropertySet-Alignment" : IfcRelDefinesByProperties

Protocol "IfcPropertySet-Referent" <<DefinedInThisDiagram>>
{
  Pset_Stationing
  Pset_Superelevation
  Pset_Width
  
}
IfcReferent --o| "IfcPropertySet-Referent" : IfcRelDefinesByProperties

@enduml
