@startuml 

entity IfcRoad <<DefinedInThisDiagram>>

entity IfcAlignment <<DefinedInAnotherDiagram>>

entity IfcVirtualElement <<DefinedInAnotherDiagram>>

protocol "IfcPropertySet-Road" <<DefinedInThisDiagram>>
{
  Pset_RoadDesignCriteriaCommon
}

entity IfcPavement <<DefinedInAnotherDiagram>>

IfcRoad --o{ IfcPavement : IfcRelContainedInSpatialStructure
IfcRoad --o{ IfcVirtualElement : IfcRelContainedInSpatialStructure

IfcRoad --o| "IfcPropertySet-Road" : IfcRelDefinesByProperties

IfcRoad--||IfcAlignment : IfcRelReferencedInSpatialStructure

@enduml
