@startuml 

entity IfcCourse <<DefinedInThisDiagram>>
{
  ObjectPlacement
  Representation
  ..
  ConnectedTo
  ConnectedFrom
}

entity IfcClassificationReference <<UndefinedEntity>>
IfcCourse --|{ IfcClassificationReference : IfcRelAssociatesClassification

entity "IfcProductDefinitionShape-TINwithBreaklines" <<DefinedInAnotherDiagram>>
IfcCourse::Representation --|| "IfcProductDefinitionShape-TINwithBreaklines"

entity IfcLocalPlacement <<UndefinedEntity>>
IfcCourse::ObjectPlacement --|| IfcLocalPlacement

protocol "IfcPropertySet-Course" <<DefinedInThisDiagram>>
{
    Pset_CourseCommon
    Pset_BoundedCourseCommon
    Pset_CourseApplicationConditions
}
IfcCourse --o{ "IfcPropertySet-Course" : IfcRelDefinesByProperties

protocol "IfcPropertySet-bSFCourse" <<DefinedInThisDiagram>>
{
    bSF_Pset_CourseCommon
    bSF_Pset_SurfaceCourse
}
IfcCourse --o{ "IfcPropertySet-bSFCourse" : IfcRelDefinesByProperties

protocol "IfcElementQuantity-Course" <<DefinedInThisDiagram>>
{
    Qto_CourseBaseQuantities
}
IfcCourse --o| "IfcElementQuantity-Course" : IfcRelDefinesByProperties

entity "IfcRelConnectsElements-Course" <<DefinedInThisDiagram>>
{
  RelatingElement
  RelatedElement
}
IfcCourse::ConnectedFrom --o{ "IfcRelConnectsElements-Course::RelatedElement" 


entity "IfcEarthWorksCut-Rock" <<DefinedInAnotherDiagram>>
entity "IfcEarthWorksCut-Soil" <<DefinedInAnotherDiagram>>
entity IfcEarthWorksFill <<DefinedInAnotherDiagram>>

<> choice
"IfcRelConnectsElements-Course::RelatingElement" - choice
choice - IfcCourse::ConnectedTo
choice - "IfcEarthWorksCut-Rock"
choice - "IfcEarthWorksCut-Soil"
choice - IfcEarthWorksFill

@enduml
