@startuml 

entity "IfcProductDefinitionShape-BrepwithBreaklines" <<DefinedInThisDiagram>>
{

  Representations
}

entity "IfcShapeRepresentation-Breaklines" <<DefinedInAnotherDiagram>>

entity IfcShapeAspect <<DefinedInAnotherDiagram>>

"IfcProductDefinitionShape-BrepwithBreaklines"--o{IfcShapeAspect

entity "IfcShapeRepresentation-Brep" <<DefinedInThisDiagram>>
{
  *RepresentationIdentifier : Body
  *RepresentationType : Tessellation
  Items
  +OfShapeAspect : $
}

entity IfcTriangulatedFaceSet <<DefinedInThisDiagram>>
{
  *Closed : boolean = TRUE
}

"IfcProductDefinitionShape-BrepwithBreaklines::Representations" --|| "IfcShapeRepresentation-Brep"
"IfcProductDefinitionShape-BrepwithBreaklines::Representations" --o| "IfcShapeRepresentation-Breaklines"

"IfcShapeRepresentation-Brep::Items"--||IfcTriangulatedFaceSet


@enduml


