@startuml 

entity IfcProject <<DefinedInThisDiagram>>
{
  RepresentationContexts
  UnitsInContext
}

entity IfcGeometricRepresentationContext-3D <<DefinedInAnotherDiagram>>

entity IfcUnitAssignment <<UndefinedEntity>>

entity IfcAlignment <<DefinedInAnotherDiagram>>
IfcProject --o{ IfcAlignment : IfcRelAggregates

entity IfcSite <<DefinedInAnotherDiagram>>
IfcProject --|{ IfcSite : IfcRelAggregates


entity IfcClassification <<UndefinedEntity>>

IfcProject::RepresentationContexts --|| "IfcGeometricRepresentationContext-3D"
IfcProject::UnitsInContext --|| IfcUnitAssignment
IfcProject --|{IfcClassification : IfcRelAssociatesClassification

@enduml
