@startuml 

entity IfcSite <<DefinedInThisDiagram>>
{
  *ObjectPlacement
  *Representation
  ..
  +IsDecomposedBy
  +HasAssociations
  +IsDefinedBy
  *ContainsElements
}


entity IfcProject <<DefinedInAnotherDiagram>>
entity IfcRoad <<DefinedInAnotherDiagram>> 

IfcProject||--IfcSite::Decomposes : IfcRelAggregates

IfcSite::IsDecomposedBy--o{IfcRoad : IfcRelAggregates

protocol "IfcPropertySet-PsetSite" <<DefinedInThisDiagram>>
{
  ==
  Pset_Address
  Pset_LandRegistration
  Pset_SiteCommon
  Pset_SiteWeather
  etc
}

entity IfcGeomodel <<DefinedInAnotherDiagram>>
IfcSite::ContainsElements--|{IfcGeomodel : IfcRelContainedInSpatialStructure

protocol "IfcPropertySet-bSFSite" <<DefinedInThisDiagram>>
{
  ==
  bSF_SiteCommon
  etc
}

protocol "IfcQuantitySetSite" <<DefinedInThisDiagram>>
{
  ==
  Qto_SiteBaseQuantities
  etc
}


entity IfcClassificationReference <<DefinedInAnotherDiagram>>
IfcSite::HasAssociations --o{ IfcClassificationReference : IfcRelAssociatesClassification

entity "IfcProductDefinitionShape-Footprint" <<UndefinedEntity>>
IfcSite::Representation --o| "IfcProductDefinitionShape-Footprint"

entity IfcLocalPlacement <<UndefinedEntity>>
IfcSite::ObjectPlacement--||IfcLocalPlacement


IfcSite::IsDefinedBy --o{ "IfcPropertySet-PsetSite"
IfcSite::IsDefinedBy --o{ "IfcPropertySet-bSFSite"
IfcSite::IsDefinedBy --o{ "IfcQuantitySetSite"


@enduml
