@startuml 

entity IfcGeomodel <<DefinedInThisDiagram>>
{
  ObjectPlacement
  Representation
}


entity IfcLocalPlacement <<UndefinedEntity>>
"IfcGeomodel::ObjectPlacement" --o| IfcLocalPlacement

entity "IfcProductDefinitionShape-TINwithBreaklines" <<DefinedInAnotherDiagram>>
"IfcGeomodel::Representation" --o| "IfcProductDefinitionShape-TINwithBreaklines"

entity IfcGeotechnicalStratum <<DefinedInAnotherDiagram>>

IfcGeomodel --|{IfcGeotechnicalStratum : IfcRelAggregates


@enduml
