@startuml 

entity "IfcProductDefinitionShape-TIN" <<DefinedInThisDiagram>>
{
  Representations
  +HasShapeAspects : $
}

entity "IfcShapeRepresentation-TIN" <<DefinedInThisDiagram>>
{
  *RepresentationIdentifier : text = Body
  *RepresentationType : text = Tessellation
  Items
  +OfShapeAspect : $
}

entity IfcTriangulatedIrregularNetwork <<UndefinedEntity>>

"IfcProductDefinitionShape-TIN::Representations" --|| "IfcShapeRepresentation-TIN::OfProductRepresentation"

"IfcShapeRepresentation-TIN::Items"--||IfcTriangulatedIrregularNetwork

@enduml


