@startuml 


entity "IfcGeotechnicalStratum-Terrain" <<DefinedInThisDiagram>>
{
  ObjectPlacement
  Representation
  *PredefinedType : text = SOLID | VOID | WATER
}

entity "IfcEarthWorksCut-Soil" <<DefinedInAnotherDiagram>>

entity IfcClassificationReference <<UndefinedEntity>>
"IfcGeotechnicalStratum-Terrain" --|{ IfcClassificationReference : IfcRelAssociatesClassification

entity IfcLocalPlacement <<UndefinedEntity>>
"IfcGeotechnicalStratum-Terrain::ObjectPlacement" --|| IfcLocalPlacement

protocol "IfcPropertySet-bSFStratum" <<DefinedInThisDiagram>>
{
    bSF_Pset_StratumCommon
}

"IfcGeotechnicalStratum-Terrain" --o| "IfcPropertySet-bSFStratum" : IfcRelDefinesByProperties
entity "IfcProductDefinitionShape-TIN" <<DefinedInAnotherDiagram>>
"IfcGeotechnicalStratum-Terrain::Representation" --|| "IfcProductDefinitionShape-TIN"

"IfcGeotechnicalStratum-Terrain" --o{ "IfcEarthWorksCut-Soil": IfcRelVoidsElement

@enduml
