@startuml 

entity "IfcProductDefinitionShape-Footprint" <<DefinedInThisDiagram>>
{
  Representations
  +HasShapeAspects : $
}

entity "IfcShapeRepresentation-Footprint" <<DefinedInThisDiagram>>
{
  *RepresentationIdentifier : text = FootPrint
  *RepresentationType : text = GeometricCurveSet
  Items
  OfProductRepresentation
  +OfShapeAspect : $
}

entity IfcGeometricCurveSet <<UndefinedEntity>>

"IfcProductDefinitionShape-Footprint::Representations" --|| "IfcShapeRepresentation-Footprint::OfProductRepresentation"


"IfcShapeRepresentation-Footprint::Items"--|{ IfcGeometricCurveSet

@enduml


