@startuml 

note "IN <u>THIS</u> DIAGRAM:\n Hierarchical relationships (containment, aggregation, voiding): solid line\n all others (references): dashed line" as N0


entity IFC_step_file <<DefinedInAnotherDiagram>>

entity IfcProject <<DefinedInAnotherDiagram>>
IFC_step_file--||IfcProject

entity IfcSite <<DefinedInAnotherDiagram>>
IfcProject||--|{IfcSite : IfcRelAggregates


entity IfcRoad <<DefinedInAnotherDiagram>> 
IfcSite||--o{IfcRoad : IfcRelAggregates


entity IfcVirtualElement <<DefinedInAnotherDiagram>>
IfcRoad||--o{IfcVirtualElement : IfcRelContainedInSpatialStructure

entity IfcGeomodel <<DefinedInAnotherDiagram>>

IfcSite||--o{IfcGeomodel : IfcRelContainedInSpatialStructure

entity IfcGeotechnicalStratum <<DefinedInAnotherDiagram>>
IfcGeomodel||--|{IfcGeotechnicalStratum:IfcRelAggregates


entity IfcPavement <<DefinedInAnotherDiagram>>
IfcRoad||--|{IfcPavement : IfcRelContainedInSpatialStructure

entity IfcEarthWorksCut <<DefinedInAnotherDiagram>>
IfcRoad}o..IfcEarthWorksCut: IfcRelReferencedInSpatialStructure


IfcGeotechnicalStratum||--o{IfcEarthWorksCut : IfcRelVoidsElement

entity IfcEarthWorksFill <<DefinedInAnotherDiagram>>
IfcRoad||--|{IfcEarthWorksFill : IfcRelContainedInSpatialStructure

entity IfcCourse <<DefinedInAnotherDiagram>>
IfcPavement||--|{IfcCourse :IfcRelAggregates

entity IfcKerb <<DefinedInAnotherDiagram>>
IfcPavement||--o{IfcKerb :IfcRelAggregates

entity IfcAlignment <<DefinedInAnotherDiagram>>
IfcProject||--o{IfcAlignment : IfcRelAggregates

IfcRoad||..||IfcAlignment : IfcRelReferencedInSpatialStructure

@enduml
