@startuml 

entity IfcGeomodel <<DefinedInThisDiagram>>
{
  ObjectPlacement
  Representation
}


entity IfcLocalPlacement <<UndefinedEntity>>
"IfcGeomodel::ObjectPlacement" --|| IfcLocalPlacement

entity "IfcProductDefinitionShape-TINwithBreaklines" <<DefinedInAnotherDiagram>>
"IfcGeomodel::Representation" --|| "IfcProductDefinitionShape-TINwithBreaklines"

entity IfcGeotechnicalStratum <<DefinedInAnotherDiagram>>

IfcGeomodel --|{IfcGeotechnicalStratum : IfcRelAggregates


@enduml
