@startuml 


entity IfcPavement <<DefinedInThisDiagram>>
{
  ObjectPlacement = $
  Representation = $
}

protocol "IfcPropertySet-Pavement" <<DefinedInThisDiagram>>
{
    Pset_PavementCommon
}

IfcPavement --o{ "IfcPropertySet-Pavement" : IfcRelDefinesByProperties


protocol "IfcElementQuantity-Pavement" <<DefinedInThisDiagram>>
{
    Qto_PavementBaseQuantities
}
IfcPavement --o| "IfcElementQuantity-Pavement" : IfcRelDefinesByProperties

entity IfcCourse <<DefinedInAnotherDiagram>>
entity IfcKerb <<DefinedInAnotherDiagram>>

entity IfcClassificationReference <<UndefinedEntity>>
IfcPavement --o{ IfcClassificationReference : IfcRelAssociatesClassification


IfcPavement--{IfcCourse : IfcRelAggregates
IfcPavement--o{IfcKerb : IfcRelAggregates



@enduml
