@startuml 

entity IfcSite <<DefinedInThisDiagram>>
{
  ObjectPlacement
  Representation
}

entity IfcRoad <<DefinedInAnotherDiagram>> 

IfcSite--o{IfcRoad : IfcRelAggregates

protocol "IfcPropertySet-Site" <<UndefinedEntity>>
{
  Pset_Address
  Pset_LandRegistration
  Pset_SiteCommon
  Pset_SiteWeather
}

entity IfcGeomodel <<DefinedInAnotherDiagram>>
IfcSite::ContainsElements--o{IfcGeomodel : IfcRelContainedInSpatialStructure


entity "IfcProductDefinitionShape-Footprint" <<DefinedInAnotherDiagram>>
IfcSite::Representation --o| "IfcProductDefinitionShape-Footprint"

entity IfcLocalPlacement <<UndefinedEntity>>
IfcSite::ObjectPlacement--||IfcLocalPlacement



@enduml
