@startuml 

entity "IfcProductDefinitionShape-TINwithBreaklines" <<DefinedInThisDiagram>>
{
  Representations
}

entity "IfcShapeRepresentation-TIN" <<DefinedInAnotherDiagram>>

entity "IfcShapeRepresentation-Breaklines" <<DefinedInThisDiagram>>
{
  *RepresentationIdentifier : text = Body
  *RepresentationType : text = Curve3D
  Items
  +OfShapeAspect : $
}

entity "IfcShapeRepresentation-Breakline" <<DefinedInThisDiagram>>
{
  *RepresentationIdentifier : text = Axis
  *RepresentationType : text = Curve3D
  Items
  +OfProductRepresentation : $
}

"IfcProductDefinitionShape-TINwithBreaklines::Representations" --|| "IfcShapeRepresentation-TIN"
"IfcProductDefinitionShape-TINwithBreaklines::Representations" --o| "IfcShapeRepresentation-Breaklines"
entity IfcPolyline <<UndefinedEntity>>
"IfcShapeRepresentation-Breaklines::Items"--|{ IfcPolyline
"IfcShapeRepresentation-Breakline::Items"--||IfcPolyline

entity IfcShapeAspect <<DefinedInThisDiagram>>

IfcShapeAspect ||-- "IfcShapeRepresentation-Breakline"
IfcShapeAspect }o-- "IfcProductDefinitionShape-TINwithBreaklines"

entity IfcClassificationReference <<UndefinedEntity>>
IfcShapeAspect --|{ IfcClassificationReference : IfcExternalReferenceRelationship


@enduml


