<style>
.DefinedInThisDiagram {
    BackgroundColor LightGreen
}
.DefinedInAnotherDiagram {
    BackgroundColor LightBlue
}
.UndefinedEntity{
    BackgroundColor #FFFFFF
    LineStyle 1-0
}
</style>
hide stereotype
hide <<DefinedInAnotherDiagram>> members
hide <<UndefinedEntity>> members
hide <<DefinedInThisDiagram>> empty methods